### ISSUE TITLE
Organizations API

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-office#10]

**Comment by flbulgarelli** [comment]
It should allow creation, deletion and update of organizations, as described on README. 

At least the following fields must be included in the organization model: 

*  contact email
* name
* books - identified by slug.
   * Today an organization supports only one book, but the new CRUD should assume one or more. 
* locale - at least `es_AR` and `en_US`
* css theme - a sass or css string. 

Please update docs accordingly.

**Comment by flbulgarelli** [comment]
Some of these task may be already done. Please review them and add what is missing.

**Comment by rodri042** [comment]
@aguspina 

Sigo sin tener permisos en el repo parece :confused:, ¿podrás chequear?
Sobre esto, hasta ahora asumí un montón de cosas, así que las listo acá y cualquier cosa decime:

- Los endpoints que estoy contemplando son:
GET /organizations
GET /organizations/:id
POST /organizations
PUT /organizations/:id (updates parciales)
- Salvo el **GET /organizations**, los otros 3 requiren el rol "owner" para el grant "*".
- Cualquiera que crea una organization puede ponerle private: true -no sé bien para qué es-.
- El **GET /organizations** devuelve todos que no son **private: true**, y hay un índice asociado a ese campo.
- Los campos **login_methods, description y logo_url** son opcionales.
