### ISSUE TITLE
Generate and serve static custom themes

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-office#16]
When an organization is created or updated, if a custom SASS/CSS theme is provided, a static CSS should be generated and served so that any Mumuki Platform application can include it. 

Related to https://github.com/mumuki/mumuki-laboratory/issues/688 and  https://github.com/mumuki/mumuki-office/issues/10

**Comment by flbulgarelli** [comment]
Classroom, Laboratory, Office and Bibliotheca code should be updated as part of this issue, so that it consumes such CSS.

**Comment by rodri042** [comment]
> Classroom, Laboratory, Office and Bibliotheca code should be updated as part of this issue, so that it consumes such CSS.
What about **mumuki-editor**? I don't understand the difference between *editor* and *bibliotheca*. I thought bibliotheca was only an API :confused:

**Comment by aguspina** [comment]
Bibliotheca is the new editor, and bibliotheca-api si te server

**Comment by flbulgarelli** [comment]
Related to https://github.com/mumuki/mumuki-platform/issues/226
